//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanSinhTo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChitietHoadonxuatModel
    {
        public long PK_iChitietHoadonxuatID { get; set; }
        public long FK_iHoadonxuatID { get; set; }
        public long FK_iSanphamID { get; set; }
        public int iSoluong { get; set; }
        public decimal mGia { get; set; }
    
        public virtual HoadonxuatModel tblHoadonxuat { get; set; }
        public virtual SanphamModel tblSanpham { get; set; }
    }
}
