//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanSinhTo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoadonNhapNguyenlieuModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoadonNhapNguyenlieuModel()
        {
            this.tblChitietHoadonNhapNguyenlieux = new HashSet<ChitietHoadonNhapNguyenlieuModel>();
        }
    
        public long PK_iHoadonNhapNguyenlieuID { get; set; }
        public System.DateTime tNgaylap { get; set; }
        public string sGhichu { get; set; }
        public long FK_iNguoidungID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChitietHoadonNhapNguyenlieuModel> tblChitietHoadonNhapNguyenlieux { get; set; }
        public virtual NguoidungModel tblNguoidung { get; set; }
    }
}
