//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanSinhTo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhuyenmaiModel
    {
        public long PK_iKhuyenmaiID { get; set; }
        public double fKhuyenmai { get; set; }
        public System.DateTime tNgaybatdau { get; set; }
        public System.DateTime tNgayketthuc { get; set; }
        public long FK_iSanphamID { get; set; }
    
        public virtual SanphamModel tblSanpham { get; set; }
    }
}
