//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanSinhTo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoidungModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NguoidungModel()
        {
            this.tblHoadonNhapNguyenlieux = new HashSet<HoadonNhapNguyenlieuModel>();
            this.tblHoadonxuats = new HashSet<HoadonxuatModel>();
            this.tblPhanquyens = new HashSet<PhanquyenModel>();
        }
    
        public long PK_iNguoidungID { get; set; }
        public string sTenNhanvien { get; set; }
        public string sTennguoidung { get; set; }
        public string sMatkhau { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoadonNhapNguyenlieuModel> tblHoadonNhapNguyenlieux { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoadonxuatModel> tblHoadonxuats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhanquyenModel> tblPhanquyens { get; set; }
    }
}
