//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanSinhTo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguyenlieuModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NguyenlieuModel()
        {
            this.tblChitietHoadonNhapNguyenlieux = new HashSet<ChitietHoadonNhapNguyenlieuModel>();
            this.tblChitietSanphams = new HashSet<ChitietSanphamModel>();
        }
    
        public long PK_iNguyenlieuID { get; set; }
        public string sTenNguyenlieu { get; set; }
        public string sMota { get; set; }
        public Nullable<double> iSoluong { get; set; }
        public string sXuatxu { get; set; }
        public string sHinhanh { get; set; }
        public int FK_iLoaiNguyenlieuID { get; set; }
        public bool isNgungcungcap { get; set; }
        public string sDonvi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChitietHoadonNhapNguyenlieuModel> tblChitietHoadonNhapNguyenlieux { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChitietSanphamModel> tblChitietSanphams { get; set; }
        public virtual LoaiNguyenlieuModel tblLoaiNguyenlieu { get; set; }
    }
}
