//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanSinhTo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanquyenModel
    {
        public long PK_iPhanquyenID { get; set; }
        public long FK_iNguoidungID { get; set; }
        public int FK_iQuyenID { get; set; }
        public System.DateTime tNgaybatdau { get; set; }
        public System.DateTime tNgayketthuc { get; set; }
    
        public virtual NguoidungModel tblNguoidung { get; set; }
        public virtual QuyenModel tblQuyen { get; set; }
    }
}
