//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanSinhTo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class db_QuanSinhToEntities : DbContext
    {
        public db_QuanSinhToEntities()
            : base("name=db_QuanSinhToEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BanggiaModel> BanggiaModels { get; set; }
        public virtual DbSet<ChitietHoadonNhapNguyenlieuModel> ChitietHoadonNhapNguyenlieuModels { get; set; }
        public virtual DbSet<ChitietHoadonxuatModel> ChitietHoadonxuatModels { get; set; }
        public virtual DbSet<ChitietSanphamModel> ChitietSanphamModels { get; set; }
        public virtual DbSet<HoadonNhapNguyenlieuModel> HoadonNhapNguyenlieuModels { get; set; }
        public virtual DbSet<HoadonxuatModel> HoadonxuatModels { get; set; }
        public virtual DbSet<KhuyenmaiModel> KhuyenmaiModels { get; set; }
        public virtual DbSet<LoaiNguyenlieuModel> LoaiNguyenlieuModels { get; set; }
        public virtual DbSet<LoaiSanphamModel> LoaiSanphamModels { get; set; }
        public virtual DbSet<NguoidungModel> NguoidungModels { get; set; }
        public virtual DbSet<NguyenlieuModel> NguyenlieuModels { get; set; }
        public virtual DbSet<PhanquyenModel> PhanquyenModels { get; set; }
        public virtual DbSet<QuyenModel> QuyenModels { get; set; }
        public virtual DbSet<SanphamModel> SanphamModels { get; set; }
    
        public virtual int spBanggia_DeleteByPK(Nullable<long> pK_iBanggiaID)
        {
            var pK_iBanggiaIDParameter = pK_iBanggiaID.HasValue ?
                new ObjectParameter("PK_iBanggiaID", pK_iBanggiaID) :
                new ObjectParameter("PK_iBanggiaID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spBanggia_DeleteByPK", pK_iBanggiaIDParameter);
        }
    
        public virtual ObjectResult<BanggiaModel> spBanggia_GetByPK(Nullable<long> pK_iBanggiaID)
        {
            var pK_iBanggiaIDParameter = pK_iBanggiaID.HasValue ?
                new ObjectParameter("PK_iBanggiaID", pK_iBanggiaID) :
                new ObjectParameter("PK_iBanggiaID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BanggiaModel>("spBanggia_GetByPK", pK_iBanggiaIDParameter);
        }
    
        public virtual ObjectResult<BanggiaModel> spBanggia_GetByPK(Nullable<long> pK_iBanggiaID, MergeOption mergeOption)
        {
            var pK_iBanggiaIDParameter = pK_iBanggiaID.HasValue ?
                new ObjectParameter("PK_iBanggiaID", pK_iBanggiaID) :
                new ObjectParameter("PK_iBanggiaID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BanggiaModel>("spBanggia_GetByPK", mergeOption, pK_iBanggiaIDParameter);
        }
    
        public virtual ObjectResult<Nullable<long>> spBanggia_Insert(Nullable<decimal> mGia, Nullable<System.DateTime> tNgaybatdauapdung, Nullable<long> fK_iSanphamID)
        {
            var mGiaParameter = mGia.HasValue ?
                new ObjectParameter("mGia", mGia) :
                new ObjectParameter("mGia", typeof(decimal));
    
            var tNgaybatdauapdungParameter = tNgaybatdauapdung.HasValue ?
                new ObjectParameter("tNgaybatdauapdung", tNgaybatdauapdung) :
                new ObjectParameter("tNgaybatdauapdung", typeof(System.DateTime));
    
            var fK_iSanphamIDParameter = fK_iSanphamID.HasValue ?
                new ObjectParameter("FK_iSanphamID", fK_iSanphamID) :
                new ObjectParameter("FK_iSanphamID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("spBanggia_Insert", mGiaParameter, tNgaybatdauapdungParameter, fK_iSanphamIDParameter);
        }
    
        public virtual int spBanggia_UpdateByPK(Nullable<long> pK_iBanggiaID, Nullable<decimal> mGia, Nullable<System.DateTime> tNgaybatdauapdung, Nullable<long> fK_iSanphamID)
        {
            var pK_iBanggiaIDParameter = pK_iBanggiaID.HasValue ?
                new ObjectParameter("PK_iBanggiaID", pK_iBanggiaID) :
                new ObjectParameter("PK_iBanggiaID", typeof(long));
    
            var mGiaParameter = mGia.HasValue ?
                new ObjectParameter("mGia", mGia) :
                new ObjectParameter("mGia", typeof(decimal));
    
            var tNgaybatdauapdungParameter = tNgaybatdauapdung.HasValue ?
                new ObjectParameter("tNgaybatdauapdung", tNgaybatdauapdung) :
                new ObjectParameter("tNgaybatdauapdung", typeof(System.DateTime));
    
            var fK_iSanphamIDParameter = fK_iSanphamID.HasValue ?
                new ObjectParameter("FK_iSanphamID", fK_iSanphamID) :
                new ObjectParameter("FK_iSanphamID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spBanggia_UpdateByPK", pK_iBanggiaIDParameter, mGiaParameter, tNgaybatdauapdungParameter, fK_iSanphamIDParameter);
        }
    
        public virtual int spChitietHoadonNhapNguyenlieu_DeleteByPK(Nullable<long> pK_iChitietHoadonNhapNguyenlieuID)
        {
            var pK_iChitietHoadonNhapNguyenlieuIDParameter = pK_iChitietHoadonNhapNguyenlieuID.HasValue ?
                new ObjectParameter("PK_iChitietHoadonNhapNguyenlieuID", pK_iChitietHoadonNhapNguyenlieuID) :
                new ObjectParameter("PK_iChitietHoadonNhapNguyenlieuID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spChitietHoadonNhapNguyenlieu_DeleteByPK", pK_iChitietHoadonNhapNguyenlieuIDParameter);
        }
    
        public virtual ObjectResult<ChitietHoadonNhapNguyenlieuModel> spChitietHoadonNhapNguyenlieu_GetByFK_iHoadonNhapNguyenlieuID(Nullable<long> fK_iHoadonNhapNguyenlieuID)
        {
            var fK_iHoadonNhapNguyenlieuIDParameter = fK_iHoadonNhapNguyenlieuID.HasValue ?
                new ObjectParameter("FK_iHoadonNhapNguyenlieuID", fK_iHoadonNhapNguyenlieuID) :
                new ObjectParameter("FK_iHoadonNhapNguyenlieuID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ChitietHoadonNhapNguyenlieuModel>("spChitietHoadonNhapNguyenlieu_GetByFK_iHoadonNhapNguyenlieuID", fK_iHoadonNhapNguyenlieuIDParameter);
        }
    
        public virtual ObjectResult<ChitietHoadonNhapNguyenlieuModel> spChitietHoadonNhapNguyenlieu_GetByFK_iHoadonNhapNguyenlieuID(Nullable<long> fK_iHoadonNhapNguyenlieuID, MergeOption mergeOption)
        {
            var fK_iHoadonNhapNguyenlieuIDParameter = fK_iHoadonNhapNguyenlieuID.HasValue ?
                new ObjectParameter("FK_iHoadonNhapNguyenlieuID", fK_iHoadonNhapNguyenlieuID) :
                new ObjectParameter("FK_iHoadonNhapNguyenlieuID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ChitietHoadonNhapNguyenlieuModel>("spChitietHoadonNhapNguyenlieu_GetByFK_iHoadonNhapNguyenlieuID", mergeOption, fK_iHoadonNhapNguyenlieuIDParameter);
        }
    
        public virtual ObjectResult<ChitietHoadonNhapNguyenlieuModel> spChitietHoadonNhapNguyenlieu_GetByFK_iNguyenlieuID(Nullable<long> fK_iNguyenlieuID)
        {
            var fK_iNguyenlieuIDParameter = fK_iNguyenlieuID.HasValue ?
                new ObjectParameter("FK_iNguyenlieuID", fK_iNguyenlieuID) :
                new ObjectParameter("FK_iNguyenlieuID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ChitietHoadonNhapNguyenlieuModel>("spChitietHoadonNhapNguyenlieu_GetByFK_iNguyenlieuID", fK_iNguyenlieuIDParameter);
        }
    
        public virtual ObjectResult<ChitietHoadonNhapNguyenlieuModel> spChitietHoadonNhapNguyenlieu_GetByFK_iNguyenlieuID(Nullable<long> fK_iNguyenlieuID, MergeOption mergeOption)
        {
            var fK_iNguyenlieuIDParameter = fK_iNguyenlieuID.HasValue ?
                new ObjectParameter("FK_iNguyenlieuID", fK_iNguyenlieuID) :
                new ObjectParameter("FK_iNguyenlieuID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ChitietHoadonNhapNguyenlieuModel>("spChitietHoadonNhapNguyenlieu_GetByFK_iNguyenlieuID", mergeOption, fK_iNguyenlieuIDParameter);
        }
    
        public virtual ObjectResult<ChitietHoadonNhapNguyenlieuModel> spChitietHoadonNhapNguyenlieu_GetByPK(Nullable<long> pK_iChitietHoadonNhapNguyenlieuID)
        {
            var pK_iChitietHoadonNhapNguyenlieuIDParameter = pK_iChitietHoadonNhapNguyenlieuID.HasValue ?
                new ObjectParameter("PK_iChitietHoadonNhapNguyenlieuID", pK_iChitietHoadonNhapNguyenlieuID) :
                new ObjectParameter("PK_iChitietHoadonNhapNguyenlieuID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ChitietHoadonNhapNguyenlieuModel>("spChitietHoadonNhapNguyenlieu_GetByPK", pK_iChitietHoadonNhapNguyenlieuIDParameter);
        }
    
        public virtual ObjectResult<ChitietHoadonNhapNguyenlieuModel> spChitietHoadonNhapNguyenlieu_GetByPK(Nullable<long> pK_iChitietHoadonNhapNguyenlieuID, MergeOption mergeOption)
        {
            var pK_iChitietHoadonNhapNguyenlieuIDParameter = pK_iChitietHoadonNhapNguyenlieuID.HasValue ?
                new ObjectParameter("PK_iChitietHoadonNhapNguyenlieuID", pK_iChitietHoadonNhapNguyenlieuID) :
                new ObjectParameter("PK_iChitietHoadonNhapNguyenlieuID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ChitietHoadonNhapNguyenlieuModel>("spChitietHoadonNhapNguyenlieu_GetByPK", mergeOption, pK_iChitietHoadonNhapNguyenlieuIDParameter);
        }
    
        public virtual ObjectResult<Nullable<long>> spChitietHoadonNhapNguyenlieu_Insert(Nullable<long> fK_iHoadonNhapNguyenlieuID, Nullable<long> fK_iNguyenlieuID, Nullable<int> iSoluong, Nullable<decimal> mGia)
        {
            var fK_iHoadonNhapNguyenlieuIDParameter = fK_iHoadonNhapNguyenlieuID.HasValue ?
                new ObjectParameter("FK_iHoadonNhapNguyenlieuID", fK_iHoadonNhapNguyenlieuID) :
                new ObjectParameter("FK_iHoadonNhapNguyenlieuID", typeof(long));
    
            var fK_iNguyenlieuIDParameter = fK_iNguyenlieuID.HasValue ?
                new ObjectParameter("FK_iNguyenlieuID", fK_iNguyenlieuID) :
                new ObjectParameter("FK_iNguyenlieuID", typeof(long));
    
            var iSoluongParameter = iSoluong.HasValue ?
                new ObjectParameter("iSoluong", iSoluong) :
                new ObjectParameter("iSoluong", typeof(int));
    
            var mGiaParameter = mGia.HasValue ?
                new ObjectParameter("mGia", mGia) :
                new ObjectParameter("mGia", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("spChitietHoadonNhapNguyenlieu_Insert", fK_iHoadonNhapNguyenlieuIDParameter, fK_iNguyenlieuIDParameter, iSoluongParameter, mGiaParameter);
        }
    
        public virtual int spChitietHoadonNhapNguyenlieu_UpdateByPK(Nullable<long> pK_iChitietHoadonNhapNguyenlieuID, Nullable<long> fK_iHoadonNhapNguyenlieuID, Nullable<long> fK_iNguyenlieuID, Nullable<int> iSoluong, Nullable<decimal> mGia)
        {
            var pK_iChitietHoadonNhapNguyenlieuIDParameter = pK_iChitietHoadonNhapNguyenlieuID.HasValue ?
                new ObjectParameter("PK_iChitietHoadonNhapNguyenlieuID", pK_iChitietHoadonNhapNguyenlieuID) :
                new ObjectParameter("PK_iChitietHoadonNhapNguyenlieuID", typeof(long));
    
            var fK_iHoadonNhapNguyenlieuIDParameter = fK_iHoadonNhapNguyenlieuID.HasValue ?
                new ObjectParameter("FK_iHoadonNhapNguyenlieuID", fK_iHoadonNhapNguyenlieuID) :
                new ObjectParameter("FK_iHoadonNhapNguyenlieuID", typeof(long));
    
            var fK_iNguyenlieuIDParameter = fK_iNguyenlieuID.HasValue ?
                new ObjectParameter("FK_iNguyenlieuID", fK_iNguyenlieuID) :
                new ObjectParameter("FK_iNguyenlieuID", typeof(long));
    
            var iSoluongParameter = iSoluong.HasValue ?
                new ObjectParameter("iSoluong", iSoluong) :
                new ObjectParameter("iSoluong", typeof(int));
    
            var mGiaParameter = mGia.HasValue ?
                new ObjectParameter("mGia", mGia) :
                new ObjectParameter("mGia", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spChitietHoadonNhapNguyenlieu_UpdateByPK", pK_iChitietHoadonNhapNguyenlieuIDParameter, fK_iHoadonNhapNguyenlieuIDParameter, fK_iNguyenlieuIDParameter, iSoluongParameter, mGiaParameter);
        }
    
        public virtual int spChitietHoadonxuat_DeleteByPK(Nullable<long> pK_iChitietHoadonxuatID)
        {
            var pK_iChitietHoadonxuatIDParameter = pK_iChitietHoadonxuatID.HasValue ?
                new ObjectParameter("PK_iChitietHoadonxuatID", pK_iChitietHoadonxuatID) :
                new ObjectParameter("PK_iChitietHoadonxuatID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spChitietHoadonxuat_DeleteByPK", pK_iChitietHoadonxuatIDParameter);
        }
    
        public virtual ObjectResult<ChitietHoadonxuatModel> spChitietHoadonxuat_GetByFK_iHoadonxuatID(Nullable<long> fK_iHoadonxuatID)
        {
            var fK_iHoadonxuatIDParameter = fK_iHoadonxuatID.HasValue ?
                new ObjectParameter("FK_iHoadonxuatID", fK_iHoadonxuatID) :
                new ObjectParameter("FK_iHoadonxuatID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ChitietHoadonxuatModel>("spChitietHoadonxuat_GetByFK_iHoadonxuatID", fK_iHoadonxuatIDParameter);
        }
    
        public virtual ObjectResult<ChitietHoadonxuatModel> spChitietHoadonxuat_GetByFK_iHoadonxuatID(Nullable<long> fK_iHoadonxuatID, MergeOption mergeOption)
        {
            var fK_iHoadonxuatIDParameter = fK_iHoadonxuatID.HasValue ?
                new ObjectParameter("FK_iHoadonxuatID", fK_iHoadonxuatID) :
                new ObjectParameter("FK_iHoadonxuatID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ChitietHoadonxuatModel>("spChitietHoadonxuat_GetByFK_iHoadonxuatID", mergeOption, fK_iHoadonxuatIDParameter);
        }
    
        public virtual ObjectResult<ChitietHoadonxuatModel> spChitietHoadonxuat_GetByFK_iSanphamID(Nullable<long> fK_iSanphamID)
        {
            var fK_iSanphamIDParameter = fK_iSanphamID.HasValue ?
                new ObjectParameter("FK_iSanphamID", fK_iSanphamID) :
                new ObjectParameter("FK_iSanphamID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ChitietHoadonxuatModel>("spChitietHoadonxuat_GetByFK_iSanphamID", fK_iSanphamIDParameter);
        }
    
        public virtual ObjectResult<ChitietHoadonxuatModel> spChitietHoadonxuat_GetByFK_iSanphamID(Nullable<long> fK_iSanphamID, MergeOption mergeOption)
        {
            var fK_iSanphamIDParameter = fK_iSanphamID.HasValue ?
                new ObjectParameter("FK_iSanphamID", fK_iSanphamID) :
                new ObjectParameter("FK_iSanphamID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ChitietHoadonxuatModel>("spChitietHoadonxuat_GetByFK_iSanphamID", mergeOption, fK_iSanphamIDParameter);
        }
    
        public virtual ObjectResult<ChitietHoadonxuatModel> spChitietHoadonxuat_GetByPK(Nullable<long> pK_iChitietHoadonxuatID)
        {
            var pK_iChitietHoadonxuatIDParameter = pK_iChitietHoadonxuatID.HasValue ?
                new ObjectParameter("PK_iChitietHoadonxuatID", pK_iChitietHoadonxuatID) :
                new ObjectParameter("PK_iChitietHoadonxuatID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ChitietHoadonxuatModel>("spChitietHoadonxuat_GetByPK", pK_iChitietHoadonxuatIDParameter);
        }
    
        public virtual ObjectResult<ChitietHoadonxuatModel> spChitietHoadonxuat_GetByPK(Nullable<long> pK_iChitietHoadonxuatID, MergeOption mergeOption)
        {
            var pK_iChitietHoadonxuatIDParameter = pK_iChitietHoadonxuatID.HasValue ?
                new ObjectParameter("PK_iChitietHoadonxuatID", pK_iChitietHoadonxuatID) :
                new ObjectParameter("PK_iChitietHoadonxuatID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ChitietHoadonxuatModel>("spChitietHoadonxuat_GetByPK", mergeOption, pK_iChitietHoadonxuatIDParameter);
        }
    
        public virtual ObjectResult<Nullable<long>> spChitietHoadonxuat_Insert(Nullable<long> fK_iHoadonxuatID, Nullable<long> fK_iSanphamID, Nullable<int> iSoluong, Nullable<decimal> mGia)
        {
            var fK_iHoadonxuatIDParameter = fK_iHoadonxuatID.HasValue ?
                new ObjectParameter("FK_iHoadonxuatID", fK_iHoadonxuatID) :
                new ObjectParameter("FK_iHoadonxuatID", typeof(long));
    
            var fK_iSanphamIDParameter = fK_iSanphamID.HasValue ?
                new ObjectParameter("FK_iSanphamID", fK_iSanphamID) :
                new ObjectParameter("FK_iSanphamID", typeof(long));
    
            var iSoluongParameter = iSoluong.HasValue ?
                new ObjectParameter("iSoluong", iSoluong) :
                new ObjectParameter("iSoluong", typeof(int));
    
            var mGiaParameter = mGia.HasValue ?
                new ObjectParameter("mGia", mGia) :
                new ObjectParameter("mGia", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("spChitietHoadonxuat_Insert", fK_iHoadonxuatIDParameter, fK_iSanphamIDParameter, iSoluongParameter, mGiaParameter);
        }
    
        public virtual int spChitietHoadonxuat_UpdateByPK(Nullable<long> pK_iChitietHoadonxuatID, Nullable<long> fK_iHoadonxuatID, Nullable<long> fK_iSanphamID, Nullable<int> iSoluong, Nullable<double> mGia)
        {
            var pK_iChitietHoadonxuatIDParameter = pK_iChitietHoadonxuatID.HasValue ?
                new ObjectParameter("PK_iChitietHoadonxuatID", pK_iChitietHoadonxuatID) :
                new ObjectParameter("PK_iChitietHoadonxuatID", typeof(long));
    
            var fK_iHoadonxuatIDParameter = fK_iHoadonxuatID.HasValue ?
                new ObjectParameter("FK_iHoadonxuatID", fK_iHoadonxuatID) :
                new ObjectParameter("FK_iHoadonxuatID", typeof(long));
    
            var fK_iSanphamIDParameter = fK_iSanphamID.HasValue ?
                new ObjectParameter("FK_iSanphamID", fK_iSanphamID) :
                new ObjectParameter("FK_iSanphamID", typeof(long));
    
            var iSoluongParameter = iSoluong.HasValue ?
                new ObjectParameter("iSoluong", iSoluong) :
                new ObjectParameter("iSoluong", typeof(int));
    
            var mGiaParameter = mGia.HasValue ?
                new ObjectParameter("mGia", mGia) :
                new ObjectParameter("mGia", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spChitietHoadonxuat_UpdateByPK", pK_iChitietHoadonxuatIDParameter, fK_iHoadonxuatIDParameter, fK_iSanphamIDParameter, iSoluongParameter, mGiaParameter);
        }
    
        public virtual int spChitietSanpham_DeleteByPK(Nullable<long> pK_iChitietSanphamID)
        {
            var pK_iChitietSanphamIDParameter = pK_iChitietSanphamID.HasValue ?
                new ObjectParameter("PK_iChitietSanphamID", pK_iChitietSanphamID) :
                new ObjectParameter("PK_iChitietSanphamID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spChitietSanpham_DeleteByPK", pK_iChitietSanphamIDParameter);
        }
    
        public virtual ObjectResult<ChitietSanphamModel> spChitietSanpham_GetByFK_iNguyenlieuID(Nullable<long> fK_iNguyenlieuID)
        {
            var fK_iNguyenlieuIDParameter = fK_iNguyenlieuID.HasValue ?
                new ObjectParameter("FK_iNguyenlieuID", fK_iNguyenlieuID) :
                new ObjectParameter("FK_iNguyenlieuID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ChitietSanphamModel>("spChitietSanpham_GetByFK_iNguyenlieuID", fK_iNguyenlieuIDParameter);
        }
    
        public virtual ObjectResult<ChitietSanphamModel> spChitietSanpham_GetByFK_iNguyenlieuID(Nullable<long> fK_iNguyenlieuID, MergeOption mergeOption)
        {
            var fK_iNguyenlieuIDParameter = fK_iNguyenlieuID.HasValue ?
                new ObjectParameter("FK_iNguyenlieuID", fK_iNguyenlieuID) :
                new ObjectParameter("FK_iNguyenlieuID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ChitietSanphamModel>("spChitietSanpham_GetByFK_iNguyenlieuID", mergeOption, fK_iNguyenlieuIDParameter);
        }
    
        public virtual ObjectResult<ChitietSanphamModel> spChitietSanpham_GetByFK_iSanphamID(Nullable<long> fK_iSanphamID)
        {
            var fK_iSanphamIDParameter = fK_iSanphamID.HasValue ?
                new ObjectParameter("FK_iSanphamID", fK_iSanphamID) :
                new ObjectParameter("FK_iSanphamID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ChitietSanphamModel>("spChitietSanpham_GetByFK_iSanphamID", fK_iSanphamIDParameter);
        }
    
        public virtual ObjectResult<ChitietSanphamModel> spChitietSanpham_GetByFK_iSanphamID(Nullable<long> fK_iSanphamID, MergeOption mergeOption)
        {
            var fK_iSanphamIDParameter = fK_iSanphamID.HasValue ?
                new ObjectParameter("FK_iSanphamID", fK_iSanphamID) :
                new ObjectParameter("FK_iSanphamID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ChitietSanphamModel>("spChitietSanpham_GetByFK_iSanphamID", mergeOption, fK_iSanphamIDParameter);
        }
    
        public virtual ObjectResult<ChitietSanphamModel> spChitietSanpham_GetByPK(Nullable<long> pK_iChitietSanphamID)
        {
            var pK_iChitietSanphamIDParameter = pK_iChitietSanphamID.HasValue ?
                new ObjectParameter("PK_iChitietSanphamID", pK_iChitietSanphamID) :
                new ObjectParameter("PK_iChitietSanphamID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ChitietSanphamModel>("spChitietSanpham_GetByPK", pK_iChitietSanphamIDParameter);
        }
    
        public virtual ObjectResult<ChitietSanphamModel> spChitietSanpham_GetByPK(Nullable<long> pK_iChitietSanphamID, MergeOption mergeOption)
        {
            var pK_iChitietSanphamIDParameter = pK_iChitietSanphamID.HasValue ?
                new ObjectParameter("PK_iChitietSanphamID", pK_iChitietSanphamID) :
                new ObjectParameter("PK_iChitietSanphamID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ChitietSanphamModel>("spChitietSanpham_GetByPK", mergeOption, pK_iChitietSanphamIDParameter);
        }
    
        public virtual ObjectResult<Nullable<long>> spChitietSanpham_Insert(Nullable<long> fK_iSanphamID, Nullable<long> fK_iNguyenlieuID, Nullable<double> fSoluong, string sGhichu)
        {
            var fK_iSanphamIDParameter = fK_iSanphamID.HasValue ?
                new ObjectParameter("FK_iSanphamID", fK_iSanphamID) :
                new ObjectParameter("FK_iSanphamID", typeof(long));
    
            var fK_iNguyenlieuIDParameter = fK_iNguyenlieuID.HasValue ?
                new ObjectParameter("FK_iNguyenlieuID", fK_iNguyenlieuID) :
                new ObjectParameter("FK_iNguyenlieuID", typeof(long));
    
            var fSoluongParameter = fSoluong.HasValue ?
                new ObjectParameter("fSoluong", fSoluong) :
                new ObjectParameter("fSoluong", typeof(double));
    
            var sGhichuParameter = sGhichu != null ?
                new ObjectParameter("sGhichu", sGhichu) :
                new ObjectParameter("sGhichu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("spChitietSanpham_Insert", fK_iSanphamIDParameter, fK_iNguyenlieuIDParameter, fSoluongParameter, sGhichuParameter);
        }
    
        public virtual int spChitietSanpham_Update(Nullable<long> pK_iChitietSanphamID, Nullable<long> fK_iSanphamID, Nullable<long> fK_iNguyenlieuID, Nullable<double> fSoluong, string sGhichu)
        {
            var pK_iChitietSanphamIDParameter = pK_iChitietSanphamID.HasValue ?
                new ObjectParameter("PK_iChitietSanphamID", pK_iChitietSanphamID) :
                new ObjectParameter("PK_iChitietSanphamID", typeof(long));
    
            var fK_iSanphamIDParameter = fK_iSanphamID.HasValue ?
                new ObjectParameter("FK_iSanphamID", fK_iSanphamID) :
                new ObjectParameter("FK_iSanphamID", typeof(long));
    
            var fK_iNguyenlieuIDParameter = fK_iNguyenlieuID.HasValue ?
                new ObjectParameter("FK_iNguyenlieuID", fK_iNguyenlieuID) :
                new ObjectParameter("FK_iNguyenlieuID", typeof(long));
    
            var fSoluongParameter = fSoluong.HasValue ?
                new ObjectParameter("fSoluong", fSoluong) :
                new ObjectParameter("fSoluong", typeof(double));
    
            var sGhichuParameter = sGhichu != null ?
                new ObjectParameter("sGhichu", sGhichu) :
                new ObjectParameter("sGhichu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spChitietSanpham_Update", pK_iChitietSanphamIDParameter, fK_iSanphamIDParameter, fK_iNguyenlieuIDParameter, fSoluongParameter, sGhichuParameter);
        }
    
        public virtual int spHoadonNhapNguyenlieu_DeleteByPK(Nullable<long> pK_iHoadonNhapNguyenlieuID)
        {
            var pK_iHoadonNhapNguyenlieuIDParameter = pK_iHoadonNhapNguyenlieuID.HasValue ?
                new ObjectParameter("PK_iHoadonNhapNguyenlieuID", pK_iHoadonNhapNguyenlieuID) :
                new ObjectParameter("PK_iHoadonNhapNguyenlieuID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spHoadonNhapNguyenlieu_DeleteByPK", pK_iHoadonNhapNguyenlieuIDParameter);
        }
    
        public virtual ObjectResult<HoadonNhapNguyenlieuModel> spHoadonNhapNguyenlieu_GetByFK_iNguoidungID(Nullable<long> fK_iNguoidungID)
        {
            var fK_iNguoidungIDParameter = fK_iNguoidungID.HasValue ?
                new ObjectParameter("FK_iNguoidungID", fK_iNguoidungID) :
                new ObjectParameter("FK_iNguoidungID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HoadonNhapNguyenlieuModel>("spHoadonNhapNguyenlieu_GetByFK_iNguoidungID", fK_iNguoidungIDParameter);
        }
    
        public virtual ObjectResult<HoadonNhapNguyenlieuModel> spHoadonNhapNguyenlieu_GetByFK_iNguoidungID(Nullable<long> fK_iNguoidungID, MergeOption mergeOption)
        {
            var fK_iNguoidungIDParameter = fK_iNguoidungID.HasValue ?
                new ObjectParameter("FK_iNguoidungID", fK_iNguoidungID) :
                new ObjectParameter("FK_iNguoidungID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HoadonNhapNguyenlieuModel>("spHoadonNhapNguyenlieu_GetByFK_iNguoidungID", mergeOption, fK_iNguoidungIDParameter);
        }
    
        public virtual ObjectResult<HoadonNhapNguyenlieuModel> spHoadonNhapNguyenlieu_GetByPK(Nullable<long> pK_iHoadonNhapNguyenlieuID)
        {
            var pK_iHoadonNhapNguyenlieuIDParameter = pK_iHoadonNhapNguyenlieuID.HasValue ?
                new ObjectParameter("PK_iHoadonNhapNguyenlieuID", pK_iHoadonNhapNguyenlieuID) :
                new ObjectParameter("PK_iHoadonNhapNguyenlieuID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HoadonNhapNguyenlieuModel>("spHoadonNhapNguyenlieu_GetByPK", pK_iHoadonNhapNguyenlieuIDParameter);
        }
    
        public virtual ObjectResult<HoadonNhapNguyenlieuModel> spHoadonNhapNguyenlieu_GetByPK(Nullable<long> pK_iHoadonNhapNguyenlieuID, MergeOption mergeOption)
        {
            var pK_iHoadonNhapNguyenlieuIDParameter = pK_iHoadonNhapNguyenlieuID.HasValue ?
                new ObjectParameter("PK_iHoadonNhapNguyenlieuID", pK_iHoadonNhapNguyenlieuID) :
                new ObjectParameter("PK_iHoadonNhapNguyenlieuID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HoadonNhapNguyenlieuModel>("spHoadonNhapNguyenlieu_GetByPK", mergeOption, pK_iHoadonNhapNguyenlieuIDParameter);
        }
    
        public virtual ObjectResult<Nullable<long>> spHoadonNhapNguyenlieu_Insert(Nullable<System.DateTime> tNgaylap, string sGhichu, Nullable<long> fK_iNguoidungID)
        {
            var tNgaylapParameter = tNgaylap.HasValue ?
                new ObjectParameter("tNgaylap", tNgaylap) :
                new ObjectParameter("tNgaylap", typeof(System.DateTime));
    
            var sGhichuParameter = sGhichu != null ?
                new ObjectParameter("sGhichu", sGhichu) :
                new ObjectParameter("sGhichu", typeof(string));
    
            var fK_iNguoidungIDParameter = fK_iNguoidungID.HasValue ?
                new ObjectParameter("FK_iNguoidungID", fK_iNguoidungID) :
                new ObjectParameter("FK_iNguoidungID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("spHoadonNhapNguyenlieu_Insert", tNgaylapParameter, sGhichuParameter, fK_iNguoidungIDParameter);
        }
    
        public virtual int spHoadonNhapNguyenlieu_UpdateByPK(Nullable<long> pK_iHoadonNhapNguyenlieuID, Nullable<System.DateTime> tNgaylap, string sGhichu, Nullable<long> fK_iNguoidungID)
        {
            var pK_iHoadonNhapNguyenlieuIDParameter = pK_iHoadonNhapNguyenlieuID.HasValue ?
                new ObjectParameter("PK_iHoadonNhapNguyenlieuID", pK_iHoadonNhapNguyenlieuID) :
                new ObjectParameter("PK_iHoadonNhapNguyenlieuID", typeof(long));
    
            var tNgaylapParameter = tNgaylap.HasValue ?
                new ObjectParameter("tNgaylap", tNgaylap) :
                new ObjectParameter("tNgaylap", typeof(System.DateTime));
    
            var sGhichuParameter = sGhichu != null ?
                new ObjectParameter("sGhichu", sGhichu) :
                new ObjectParameter("sGhichu", typeof(string));
    
            var fK_iNguoidungIDParameter = fK_iNguoidungID.HasValue ?
                new ObjectParameter("FK_iNguoidungID", fK_iNguoidungID) :
                new ObjectParameter("FK_iNguoidungID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spHoadonNhapNguyenlieu_UpdateByPK", pK_iHoadonNhapNguyenlieuIDParameter, tNgaylapParameter, sGhichuParameter, fK_iNguoidungIDParameter);
        }
    
        public virtual int spHoadonxuat_DeleteByPK(Nullable<long> pK_iHoadonxuat)
        {
            var pK_iHoadonxuatParameter = pK_iHoadonxuat.HasValue ?
                new ObjectParameter("PK_iHoadonxuat", pK_iHoadonxuat) :
                new ObjectParameter("PK_iHoadonxuat", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spHoadonxuat_DeleteByPK", pK_iHoadonxuatParameter);
        }
    
        public virtual ObjectResult<HoadonxuatModel> spHoadonxuat_GetByFK_iNguoidungID(Nullable<long> fK_iNguoidungID)
        {
            var fK_iNguoidungIDParameter = fK_iNguoidungID.HasValue ?
                new ObjectParameter("FK_iNguoidungID", fK_iNguoidungID) :
                new ObjectParameter("FK_iNguoidungID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HoadonxuatModel>("spHoadonxuat_GetByFK_iNguoidungID", fK_iNguoidungIDParameter);
        }
    
        public virtual ObjectResult<HoadonxuatModel> spHoadonxuat_GetByFK_iNguoidungID(Nullable<long> fK_iNguoidungID, MergeOption mergeOption)
        {
            var fK_iNguoidungIDParameter = fK_iNguoidungID.HasValue ?
                new ObjectParameter("FK_iNguoidungID", fK_iNguoidungID) :
                new ObjectParameter("FK_iNguoidungID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HoadonxuatModel>("spHoadonxuat_GetByFK_iNguoidungID", mergeOption, fK_iNguoidungIDParameter);
        }
    
        public virtual ObjectResult<HoadonxuatModel> spHoadonxuat_GetByPK(Nullable<long> pK_iHoadonxuatID)
        {
            var pK_iHoadonxuatIDParameter = pK_iHoadonxuatID.HasValue ?
                new ObjectParameter("PK_iHoadonxuatID", pK_iHoadonxuatID) :
                new ObjectParameter("PK_iHoadonxuatID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HoadonxuatModel>("spHoadonxuat_GetByPK", pK_iHoadonxuatIDParameter);
        }
    
        public virtual ObjectResult<HoadonxuatModel> spHoadonxuat_GetByPK(Nullable<long> pK_iHoadonxuatID, MergeOption mergeOption)
        {
            var pK_iHoadonxuatIDParameter = pK_iHoadonxuatID.HasValue ?
                new ObjectParameter("PK_iHoadonxuatID", pK_iHoadonxuatID) :
                new ObjectParameter("PK_iHoadonxuatID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HoadonxuatModel>("spHoadonxuat_GetByPK", mergeOption, pK_iHoadonxuatIDParameter);
        }
    
        public virtual ObjectResult<Nullable<long>> spHoadonxuat_Insert(Nullable<System.DateTime> tNgaylap, string sGhichu, Nullable<long> fK_iNguoidungID)
        {
            var tNgaylapParameter = tNgaylap.HasValue ?
                new ObjectParameter("tNgaylap", tNgaylap) :
                new ObjectParameter("tNgaylap", typeof(System.DateTime));
    
            var sGhichuParameter = sGhichu != null ?
                new ObjectParameter("sGhichu", sGhichu) :
                new ObjectParameter("sGhichu", typeof(string));
    
            var fK_iNguoidungIDParameter = fK_iNguoidungID.HasValue ?
                new ObjectParameter("FK_iNguoidungID", fK_iNguoidungID) :
                new ObjectParameter("FK_iNguoidungID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("spHoadonxuat_Insert", tNgaylapParameter, sGhichuParameter, fK_iNguoidungIDParameter);
        }
    
        public virtual int spHoadonxuat_UpdateByPK(Nullable<long> pK_iHoadonxuatID, Nullable<System.DateTime> tNgaylap, string sGhichu, Nullable<long> fK_iNguoidungID)
        {
            var pK_iHoadonxuatIDParameter = pK_iHoadonxuatID.HasValue ?
                new ObjectParameter("PK_iHoadonxuatID", pK_iHoadonxuatID) :
                new ObjectParameter("PK_iHoadonxuatID", typeof(long));
    
            var tNgaylapParameter = tNgaylap.HasValue ?
                new ObjectParameter("tNgaylap", tNgaylap) :
                new ObjectParameter("tNgaylap", typeof(System.DateTime));
    
            var sGhichuParameter = sGhichu != null ?
                new ObjectParameter("sGhichu", sGhichu) :
                new ObjectParameter("sGhichu", typeof(string));
    
            var fK_iNguoidungIDParameter = fK_iNguoidungID.HasValue ?
                new ObjectParameter("FK_iNguoidungID", fK_iNguoidungID) :
                new ObjectParameter("FK_iNguoidungID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spHoadonxuat_UpdateByPK", pK_iHoadonxuatIDParameter, tNgaylapParameter, sGhichuParameter, fK_iNguoidungIDParameter);
        }
    
        public virtual int spKhuyenmai_DeleteByPK(Nullable<long> pK_iKhuyenmaiID)
        {
            var pK_iKhuyenmaiIDParameter = pK_iKhuyenmaiID.HasValue ?
                new ObjectParameter("PK_iKhuyenmaiID", pK_iKhuyenmaiID) :
                new ObjectParameter("PK_iKhuyenmaiID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spKhuyenmai_DeleteByPK", pK_iKhuyenmaiIDParameter);
        }
    
        public virtual ObjectResult<KhuyenmaiModel> spKhuyenmai_GetByFK_iSanphamID(Nullable<long> fK_iSanphamID)
        {
            var fK_iSanphamIDParameter = fK_iSanphamID.HasValue ?
                new ObjectParameter("FK_iSanphamID", fK_iSanphamID) :
                new ObjectParameter("FK_iSanphamID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KhuyenmaiModel>("spKhuyenmai_GetByFK_iSanphamID", fK_iSanphamIDParameter);
        }
    
        public virtual ObjectResult<KhuyenmaiModel> spKhuyenmai_GetByFK_iSanphamID(Nullable<long> fK_iSanphamID, MergeOption mergeOption)
        {
            var fK_iSanphamIDParameter = fK_iSanphamID.HasValue ?
                new ObjectParameter("FK_iSanphamID", fK_iSanphamID) :
                new ObjectParameter("FK_iSanphamID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KhuyenmaiModel>("spKhuyenmai_GetByFK_iSanphamID", mergeOption, fK_iSanphamIDParameter);
        }
    
        public virtual ObjectResult<KhuyenmaiModel> spKhuyenmai_GetByPK(Nullable<long> pK_iKhuyenmaiID)
        {
            var pK_iKhuyenmaiIDParameter = pK_iKhuyenmaiID.HasValue ?
                new ObjectParameter("PK_iKhuyenmaiID", pK_iKhuyenmaiID) :
                new ObjectParameter("PK_iKhuyenmaiID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KhuyenmaiModel>("spKhuyenmai_GetByPK", pK_iKhuyenmaiIDParameter);
        }
    
        public virtual ObjectResult<KhuyenmaiModel> spKhuyenmai_GetByPK(Nullable<long> pK_iKhuyenmaiID, MergeOption mergeOption)
        {
            var pK_iKhuyenmaiIDParameter = pK_iKhuyenmaiID.HasValue ?
                new ObjectParameter("PK_iKhuyenmaiID", pK_iKhuyenmaiID) :
                new ObjectParameter("PK_iKhuyenmaiID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KhuyenmaiModel>("spKhuyenmai_GetByPK", mergeOption, pK_iKhuyenmaiIDParameter);
        }
    
        public virtual ObjectResult<Nullable<long>> spKhuyenmai_Insert(Nullable<double> fKhuyenmai, Nullable<System.DateTime> tNgaybatdau, Nullable<System.DateTime> tNgayketthuc, Nullable<long> fK_iSanphamID)
        {
            var fKhuyenmaiParameter = fKhuyenmai.HasValue ?
                new ObjectParameter("fKhuyenmai", fKhuyenmai) :
                new ObjectParameter("fKhuyenmai", typeof(double));
    
            var tNgaybatdauParameter = tNgaybatdau.HasValue ?
                new ObjectParameter("tNgaybatdau", tNgaybatdau) :
                new ObjectParameter("tNgaybatdau", typeof(System.DateTime));
    
            var tNgayketthucParameter = tNgayketthuc.HasValue ?
                new ObjectParameter("tNgayketthuc", tNgayketthuc) :
                new ObjectParameter("tNgayketthuc", typeof(System.DateTime));
    
            var fK_iSanphamIDParameter = fK_iSanphamID.HasValue ?
                new ObjectParameter("FK_iSanphamID", fK_iSanphamID) :
                new ObjectParameter("FK_iSanphamID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("spKhuyenmai_Insert", fKhuyenmaiParameter, tNgaybatdauParameter, tNgayketthucParameter, fK_iSanphamIDParameter);
        }
    
        public virtual int spKhuyenmai_UpdateByPK(Nullable<long> pK_iKhuyenmaiID, Nullable<double> fKhuyenmai, Nullable<System.DateTime> tNgaybatdau, Nullable<System.DateTime> tNgayketthuc, Nullable<long> fK_iSanphamID)
        {
            var pK_iKhuyenmaiIDParameter = pK_iKhuyenmaiID.HasValue ?
                new ObjectParameter("PK_iKhuyenmaiID", pK_iKhuyenmaiID) :
                new ObjectParameter("PK_iKhuyenmaiID", typeof(long));
    
            var fKhuyenmaiParameter = fKhuyenmai.HasValue ?
                new ObjectParameter("fKhuyenmai", fKhuyenmai) :
                new ObjectParameter("fKhuyenmai", typeof(double));
    
            var tNgaybatdauParameter = tNgaybatdau.HasValue ?
                new ObjectParameter("tNgaybatdau", tNgaybatdau) :
                new ObjectParameter("tNgaybatdau", typeof(System.DateTime));
    
            var tNgayketthucParameter = tNgayketthuc.HasValue ?
                new ObjectParameter("tNgayketthuc", tNgayketthuc) :
                new ObjectParameter("tNgayketthuc", typeof(System.DateTime));
    
            var fK_iSanphamIDParameter = fK_iSanphamID.HasValue ?
                new ObjectParameter("FK_iSanphamID", fK_iSanphamID) :
                new ObjectParameter("FK_iSanphamID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spKhuyenmai_UpdateByPK", pK_iKhuyenmaiIDParameter, fKhuyenmaiParameter, tNgaybatdauParameter, tNgayketthucParameter, fK_iSanphamIDParameter);
        }
    
        public virtual int spLoaiNguyenlieu_DeleteByPK(Nullable<int> pK_iLoaiNguyenlieuID)
        {
            var pK_iLoaiNguyenlieuIDParameter = pK_iLoaiNguyenlieuID.HasValue ?
                new ObjectParameter("PK_iLoaiNguyenlieuID", pK_iLoaiNguyenlieuID) :
                new ObjectParameter("PK_iLoaiNguyenlieuID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spLoaiNguyenlieu_DeleteByPK", pK_iLoaiNguyenlieuIDParameter);
        }
    
        public virtual ObjectResult<LoaiNguyenlieuModel> spLoaiNguyenlieu_GetByPK(Nullable<int> pK_iLoaiNguyenlieuID)
        {
            var pK_iLoaiNguyenlieuIDParameter = pK_iLoaiNguyenlieuID.HasValue ?
                new ObjectParameter("PK_iLoaiNguyenlieuID", pK_iLoaiNguyenlieuID) :
                new ObjectParameter("PK_iLoaiNguyenlieuID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LoaiNguyenlieuModel>("spLoaiNguyenlieu_GetByPK", pK_iLoaiNguyenlieuIDParameter);
        }
    
        public virtual ObjectResult<LoaiNguyenlieuModel> spLoaiNguyenlieu_GetByPK(Nullable<int> pK_iLoaiNguyenlieuID, MergeOption mergeOption)
        {
            var pK_iLoaiNguyenlieuIDParameter = pK_iLoaiNguyenlieuID.HasValue ?
                new ObjectParameter("PK_iLoaiNguyenlieuID", pK_iLoaiNguyenlieuID) :
                new ObjectParameter("PK_iLoaiNguyenlieuID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LoaiNguyenlieuModel>("spLoaiNguyenlieu_GetByPK", mergeOption, pK_iLoaiNguyenlieuIDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> spLoaiNguyenlieu_Insert(string sTenLoaiNguyenlieu, string sMota, Nullable<bool> isNgungKinhdoanh)
        {
            var sTenLoaiNguyenlieuParameter = sTenLoaiNguyenlieu != null ?
                new ObjectParameter("sTenLoaiNguyenlieu", sTenLoaiNguyenlieu) :
                new ObjectParameter("sTenLoaiNguyenlieu", typeof(string));
    
            var sMotaParameter = sMota != null ?
                new ObjectParameter("sMota", sMota) :
                new ObjectParameter("sMota", typeof(string));
    
            var isNgungKinhdoanhParameter = isNgungKinhdoanh.HasValue ?
                new ObjectParameter("IsNgungKinhdoanh", isNgungKinhdoanh) :
                new ObjectParameter("IsNgungKinhdoanh", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("spLoaiNguyenlieu_Insert", sTenLoaiNguyenlieuParameter, sMotaParameter, isNgungKinhdoanhParameter);
        }
    
        public virtual int spLoaiNguyenlieu_UpdateByPK(Nullable<int> pK_iLoaiNguyenlieuID, string sTenLoaiNguyenlieu, string sMota, Nullable<bool> isNgungKinhdoanh)
        {
            var pK_iLoaiNguyenlieuIDParameter = pK_iLoaiNguyenlieuID.HasValue ?
                new ObjectParameter("PK_iLoaiNguyenlieuID", pK_iLoaiNguyenlieuID) :
                new ObjectParameter("PK_iLoaiNguyenlieuID", typeof(int));
    
            var sTenLoaiNguyenlieuParameter = sTenLoaiNguyenlieu != null ?
                new ObjectParameter("sTenLoaiNguyenlieu", sTenLoaiNguyenlieu) :
                new ObjectParameter("sTenLoaiNguyenlieu", typeof(string));
    
            var sMotaParameter = sMota != null ?
                new ObjectParameter("sMota", sMota) :
                new ObjectParameter("sMota", typeof(string));
    
            var isNgungKinhdoanhParameter = isNgungKinhdoanh.HasValue ?
                new ObjectParameter("IsNgungKinhdoanh", isNgungKinhdoanh) :
                new ObjectParameter("IsNgungKinhdoanh", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spLoaiNguyenlieu_UpdateByPK", pK_iLoaiNguyenlieuIDParameter, sTenLoaiNguyenlieuParameter, sMotaParameter, isNgungKinhdoanhParameter);
        }
    
        public virtual int spLoaiSanpham_DeleteByPK(Nullable<int> pK_iLoaiSanphamID)
        {
            var pK_iLoaiSanphamIDParameter = pK_iLoaiSanphamID.HasValue ?
                new ObjectParameter("PK_iLoaiSanphamID", pK_iLoaiSanphamID) :
                new ObjectParameter("PK_iLoaiSanphamID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spLoaiSanpham_DeleteByPK", pK_iLoaiSanphamIDParameter);
        }
    
        public virtual ObjectResult<LoaiSanphamModel> spLoaiSanpham_GetByPK(Nullable<int> pK_iLoaiSanphamID)
        {
            var pK_iLoaiSanphamIDParameter = pK_iLoaiSanphamID.HasValue ?
                new ObjectParameter("PK_iLoaiSanphamID", pK_iLoaiSanphamID) :
                new ObjectParameter("PK_iLoaiSanphamID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LoaiSanphamModel>("spLoaiSanpham_GetByPK", pK_iLoaiSanphamIDParameter);
        }
    
        public virtual ObjectResult<LoaiSanphamModel> spLoaiSanpham_GetByPK(Nullable<int> pK_iLoaiSanphamID, MergeOption mergeOption)
        {
            var pK_iLoaiSanphamIDParameter = pK_iLoaiSanphamID.HasValue ?
                new ObjectParameter("PK_iLoaiSanphamID", pK_iLoaiSanphamID) :
                new ObjectParameter("PK_iLoaiSanphamID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LoaiSanphamModel>("spLoaiSanpham_GetByPK", mergeOption, pK_iLoaiSanphamIDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> spLoaiSanpham_Insert(string sTenLoaiSanpham, string sMota, Nullable<bool> isNgungKinhdoanh)
        {
            var sTenLoaiSanphamParameter = sTenLoaiSanpham != null ?
                new ObjectParameter("sTenLoaiSanpham", sTenLoaiSanpham) :
                new ObjectParameter("sTenLoaiSanpham", typeof(string));
    
            var sMotaParameter = sMota != null ?
                new ObjectParameter("sMota", sMota) :
                new ObjectParameter("sMota", typeof(string));
    
            var isNgungKinhdoanhParameter = isNgungKinhdoanh.HasValue ?
                new ObjectParameter("IsNgungKinhdoanh", isNgungKinhdoanh) :
                new ObjectParameter("IsNgungKinhdoanh", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("spLoaiSanpham_Insert", sTenLoaiSanphamParameter, sMotaParameter, isNgungKinhdoanhParameter);
        }
    
        public virtual int spLoaiSanpham_UpdateByPK(Nullable<int> pK_iLoaiSanphamID, string sTenLoaiSanpham, string sMota, Nullable<bool> isNgungKinhdoanh)
        {
            var pK_iLoaiSanphamIDParameter = pK_iLoaiSanphamID.HasValue ?
                new ObjectParameter("PK_iLoaiSanphamID", pK_iLoaiSanphamID) :
                new ObjectParameter("PK_iLoaiSanphamID", typeof(int));
    
            var sTenLoaiSanphamParameter = sTenLoaiSanpham != null ?
                new ObjectParameter("sTenLoaiSanpham", sTenLoaiSanpham) :
                new ObjectParameter("sTenLoaiSanpham", typeof(string));
    
            var sMotaParameter = sMota != null ?
                new ObjectParameter("sMota", sMota) :
                new ObjectParameter("sMota", typeof(string));
    
            var isNgungKinhdoanhParameter = isNgungKinhdoanh.HasValue ?
                new ObjectParameter("IsNgungKinhdoanh", isNgungKinhdoanh) :
                new ObjectParameter("IsNgungKinhdoanh", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spLoaiSanpham_UpdateByPK", pK_iLoaiSanphamIDParameter, sTenLoaiSanphamParameter, sMotaParameter, isNgungKinhdoanhParameter);
        }
    
        public virtual int spNguoidung_DeleteByPK(Nullable<long> pK_iNguoidungID)
        {
            var pK_iNguoidungIDParameter = pK_iNguoidungID.HasValue ?
                new ObjectParameter("PK_iNguoidungID", pK_iNguoidungID) :
                new ObjectParameter("PK_iNguoidungID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spNguoidung_DeleteByPK", pK_iNguoidungIDParameter);
        }
    
        public virtual ObjectResult<NguoidungModel> spNguoidung_GetByPK(Nullable<long> pK_iNguoidungID)
        {
            var pK_iNguoidungIDParameter = pK_iNguoidungID.HasValue ?
                new ObjectParameter("PK_iNguoidungID", pK_iNguoidungID) :
                new ObjectParameter("PK_iNguoidungID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NguoidungModel>("spNguoidung_GetByPK", pK_iNguoidungIDParameter);
        }
    
        public virtual ObjectResult<NguoidungModel> spNguoidung_GetByPK(Nullable<long> pK_iNguoidungID, MergeOption mergeOption)
        {
            var pK_iNguoidungIDParameter = pK_iNguoidungID.HasValue ?
                new ObjectParameter("PK_iNguoidungID", pK_iNguoidungID) :
                new ObjectParameter("PK_iNguoidungID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NguoidungModel>("spNguoidung_GetByPK", mergeOption, pK_iNguoidungIDParameter);
        }
    
        public virtual ObjectResult<Nullable<long>> spNguoidung_Insert(string sTennguoidung, string sTenNhanvien, string sMatkhau)
        {
            var sTennguoidungParameter = sTennguoidung != null ?
                new ObjectParameter("sTennguoidung", sTennguoidung) :
                new ObjectParameter("sTennguoidung", typeof(string));
    
            var sTenNhanvienParameter = sTenNhanvien != null ?
                new ObjectParameter("sTenNhanvien", sTenNhanvien) :
                new ObjectParameter("sTenNhanvien", typeof(string));
    
            var sMatkhauParameter = sMatkhau != null ?
                new ObjectParameter("sMatkhau", sMatkhau) :
                new ObjectParameter("sMatkhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("spNguoidung_Insert", sTennguoidungParameter, sTenNhanvienParameter, sMatkhauParameter);
        }
    
        public virtual int spNguoidung_Update(Nullable<long> pK_iNguoidungID, string sTennguoidung, string sTenNhanvien, string sMatkhau)
        {
            var pK_iNguoidungIDParameter = pK_iNguoidungID.HasValue ?
                new ObjectParameter("PK_iNguoidungID", pK_iNguoidungID) :
                new ObjectParameter("PK_iNguoidungID", typeof(long));
    
            var sTennguoidungParameter = sTennguoidung != null ?
                new ObjectParameter("sTennguoidung", sTennguoidung) :
                new ObjectParameter("sTennguoidung", typeof(string));
    
            var sTenNhanvienParameter = sTenNhanvien != null ?
                new ObjectParameter("sTenNhanvien", sTenNhanvien) :
                new ObjectParameter("sTenNhanvien", typeof(string));
    
            var sMatkhauParameter = sMatkhau != null ?
                new ObjectParameter("sMatkhau", sMatkhau) :
                new ObjectParameter("sMatkhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spNguoidung_Update", pK_iNguoidungIDParameter, sTennguoidungParameter, sTenNhanvienParameter, sMatkhauParameter);
        }
    
        public virtual int spNguyenlieu_DeleteByPK(Nullable<long> pK_iNguyenlieuID)
        {
            var pK_iNguyenlieuIDParameter = pK_iNguyenlieuID.HasValue ?
                new ObjectParameter("PK_iNguyenlieuID", pK_iNguyenlieuID) :
                new ObjectParameter("PK_iNguyenlieuID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spNguyenlieu_DeleteByPK", pK_iNguyenlieuIDParameter);
        }
    
        public virtual ObjectResult<NguyenlieuModel> spNguyenlieu_GetByFK_iLoaiNguyenlieuID(Nullable<int> fK_iLoaiNguyenlieuID)
        {
            var fK_iLoaiNguyenlieuIDParameter = fK_iLoaiNguyenlieuID.HasValue ?
                new ObjectParameter("FK_iLoaiNguyenlieuID", fK_iLoaiNguyenlieuID) :
                new ObjectParameter("FK_iLoaiNguyenlieuID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NguyenlieuModel>("spNguyenlieu_GetByFK_iLoaiNguyenlieuID", fK_iLoaiNguyenlieuIDParameter);
        }
    
        public virtual ObjectResult<NguyenlieuModel> spNguyenlieu_GetByFK_iLoaiNguyenlieuID(Nullable<int> fK_iLoaiNguyenlieuID, MergeOption mergeOption)
        {
            var fK_iLoaiNguyenlieuIDParameter = fK_iLoaiNguyenlieuID.HasValue ?
                new ObjectParameter("FK_iLoaiNguyenlieuID", fK_iLoaiNguyenlieuID) :
                new ObjectParameter("FK_iLoaiNguyenlieuID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NguyenlieuModel>("spNguyenlieu_GetByFK_iLoaiNguyenlieuID", mergeOption, fK_iLoaiNguyenlieuIDParameter);
        }
    
        public virtual ObjectResult<NguyenlieuModel> spNguyenlieu_GetByPK(Nullable<long> pK_iNguyenlieuID)
        {
            var pK_iNguyenlieuIDParameter = pK_iNguyenlieuID.HasValue ?
                new ObjectParameter("PK_iNguyenlieuID", pK_iNguyenlieuID) :
                new ObjectParameter("PK_iNguyenlieuID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NguyenlieuModel>("spNguyenlieu_GetByPK", pK_iNguyenlieuIDParameter);
        }
    
        public virtual ObjectResult<NguyenlieuModel> spNguyenlieu_GetByPK(Nullable<long> pK_iNguyenlieuID, MergeOption mergeOption)
        {
            var pK_iNguyenlieuIDParameter = pK_iNguyenlieuID.HasValue ?
                new ObjectParameter("PK_iNguyenlieuID", pK_iNguyenlieuID) :
                new ObjectParameter("PK_iNguyenlieuID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NguyenlieuModel>("spNguyenlieu_GetByPK", mergeOption, pK_iNguyenlieuIDParameter);
        }
    
        public virtual ObjectResult<Nullable<long>> spNguyenlieu_Insert(string sTenNguyenlieu, string sMota, Nullable<double> iSoluong, string sDonvi, string sXuatxu, string sHinhanh, Nullable<int> fK_iLoaiNguyenlieuID, Nullable<bool> isNgungcungcap)
        {
            var sTenNguyenlieuParameter = sTenNguyenlieu != null ?
                new ObjectParameter("sTenNguyenlieu", sTenNguyenlieu) :
                new ObjectParameter("sTenNguyenlieu", typeof(string));
    
            var sMotaParameter = sMota != null ?
                new ObjectParameter("sMota", sMota) :
                new ObjectParameter("sMota", typeof(string));
    
            var iSoluongParameter = iSoluong.HasValue ?
                new ObjectParameter("iSoluong", iSoluong) :
                new ObjectParameter("iSoluong", typeof(double));
    
            var sDonviParameter = sDonvi != null ?
                new ObjectParameter("sDonvi", sDonvi) :
                new ObjectParameter("sDonvi", typeof(string));
    
            var sXuatxuParameter = sXuatxu != null ?
                new ObjectParameter("sXuatxu", sXuatxu) :
                new ObjectParameter("sXuatxu", typeof(string));
    
            var sHinhanhParameter = sHinhanh != null ?
                new ObjectParameter("sHinhanh", sHinhanh) :
                new ObjectParameter("sHinhanh", typeof(string));
    
            var fK_iLoaiNguyenlieuIDParameter = fK_iLoaiNguyenlieuID.HasValue ?
                new ObjectParameter("FK_iLoaiNguyenlieuID", fK_iLoaiNguyenlieuID) :
                new ObjectParameter("FK_iLoaiNguyenlieuID", typeof(int));
    
            var isNgungcungcapParameter = isNgungcungcap.HasValue ?
                new ObjectParameter("isNgungcungcap", isNgungcungcap) :
                new ObjectParameter("isNgungcungcap", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("spNguyenlieu_Insert", sTenNguyenlieuParameter, sMotaParameter, iSoluongParameter, sDonviParameter, sXuatxuParameter, sHinhanhParameter, fK_iLoaiNguyenlieuIDParameter, isNgungcungcapParameter);
        }
    
        public virtual int spNguyenlieu_UpdateByPK(Nullable<long> pK_iNguyenlieuID, string sTenNguyenlieu, string sMota, Nullable<double> iSoluong, string sDonvi, string sXuatxu, string sHinhanh, Nullable<int> fK_iLoaiNguyenlieuID, Nullable<bool> isNgungcungcap)
        {
            var pK_iNguyenlieuIDParameter = pK_iNguyenlieuID.HasValue ?
                new ObjectParameter("PK_iNguyenlieuID", pK_iNguyenlieuID) :
                new ObjectParameter("PK_iNguyenlieuID", typeof(long));
    
            var sTenNguyenlieuParameter = sTenNguyenlieu != null ?
                new ObjectParameter("sTenNguyenlieu", sTenNguyenlieu) :
                new ObjectParameter("sTenNguyenlieu", typeof(string));
    
            var sMotaParameter = sMota != null ?
                new ObjectParameter("sMota", sMota) :
                new ObjectParameter("sMota", typeof(string));
    
            var iSoluongParameter = iSoluong.HasValue ?
                new ObjectParameter("iSoluong", iSoluong) :
                new ObjectParameter("iSoluong", typeof(double));
    
            var sDonviParameter = sDonvi != null ?
                new ObjectParameter("sDonvi", sDonvi) :
                new ObjectParameter("sDonvi", typeof(string));
    
            var sXuatxuParameter = sXuatxu != null ?
                new ObjectParameter("sXuatxu", sXuatxu) :
                new ObjectParameter("sXuatxu", typeof(string));
    
            var sHinhanhParameter = sHinhanh != null ?
                new ObjectParameter("sHinhanh", sHinhanh) :
                new ObjectParameter("sHinhanh", typeof(string));
    
            var fK_iLoaiNguyenlieuIDParameter = fK_iLoaiNguyenlieuID.HasValue ?
                new ObjectParameter("FK_iLoaiNguyenlieuID", fK_iLoaiNguyenlieuID) :
                new ObjectParameter("FK_iLoaiNguyenlieuID", typeof(int));
    
            var isNgungcungcapParameter = isNgungcungcap.HasValue ?
                new ObjectParameter("isNgungcungcap", isNgungcungcap) :
                new ObjectParameter("isNgungcungcap", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spNguyenlieu_UpdateByPK", pK_iNguyenlieuIDParameter, sTenNguyenlieuParameter, sMotaParameter, iSoluongParameter, sDonviParameter, sXuatxuParameter, sHinhanhParameter, fK_iLoaiNguyenlieuIDParameter, isNgungcungcapParameter);
        }
    
        public virtual int spPhanquyen_DeleteByPK(Nullable<long> pK_iPhanquyenID)
        {
            var pK_iPhanquyenIDParameter = pK_iPhanquyenID.HasValue ?
                new ObjectParameter("PK_iPhanquyenID", pK_iPhanquyenID) :
                new ObjectParameter("PK_iPhanquyenID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spPhanquyen_DeleteByPK", pK_iPhanquyenIDParameter);
        }
    
        public virtual ObjectResult<PhanquyenModel> spPhanquyen_GetByFK_iNguoidungID(Nullable<long> fK_iNguoidungID)
        {
            var fK_iNguoidungIDParameter = fK_iNguoidungID.HasValue ?
                new ObjectParameter("FK_iNguoidungID", fK_iNguoidungID) :
                new ObjectParameter("FK_iNguoidungID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PhanquyenModel>("spPhanquyen_GetByFK_iNguoidungID", fK_iNguoidungIDParameter);
        }
    
        public virtual ObjectResult<PhanquyenModel> spPhanquyen_GetByFK_iNguoidungID(Nullable<long> fK_iNguoidungID, MergeOption mergeOption)
        {
            var fK_iNguoidungIDParameter = fK_iNguoidungID.HasValue ?
                new ObjectParameter("FK_iNguoidungID", fK_iNguoidungID) :
                new ObjectParameter("FK_iNguoidungID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PhanquyenModel>("spPhanquyen_GetByFK_iNguoidungID", mergeOption, fK_iNguoidungIDParameter);
        }
    
        public virtual ObjectResult<PhanquyenModel> spPhanquyen_GetByFK_iQuyenID(Nullable<int> fK_iQuyenID)
        {
            var fK_iQuyenIDParameter = fK_iQuyenID.HasValue ?
                new ObjectParameter("FK_iQuyenID", fK_iQuyenID) :
                new ObjectParameter("FK_iQuyenID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PhanquyenModel>("spPhanquyen_GetByFK_iQuyenID", fK_iQuyenIDParameter);
        }
    
        public virtual ObjectResult<PhanquyenModel> spPhanquyen_GetByFK_iQuyenID(Nullable<int> fK_iQuyenID, MergeOption mergeOption)
        {
            var fK_iQuyenIDParameter = fK_iQuyenID.HasValue ?
                new ObjectParameter("FK_iQuyenID", fK_iQuyenID) :
                new ObjectParameter("FK_iQuyenID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PhanquyenModel>("spPhanquyen_GetByFK_iQuyenID", mergeOption, fK_iQuyenIDParameter);
        }
    
        public virtual ObjectResult<PhanquyenModel> spPhanquyen_GetByPK(Nullable<long> pK_iPhanquyenID)
        {
            var pK_iPhanquyenIDParameter = pK_iPhanquyenID.HasValue ?
                new ObjectParameter("PK_iPhanquyenID", pK_iPhanquyenID) :
                new ObjectParameter("PK_iPhanquyenID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PhanquyenModel>("spPhanquyen_GetByPK", pK_iPhanquyenIDParameter);
        }
    
        public virtual ObjectResult<PhanquyenModel> spPhanquyen_GetByPK(Nullable<long> pK_iPhanquyenID, MergeOption mergeOption)
        {
            var pK_iPhanquyenIDParameter = pK_iPhanquyenID.HasValue ?
                new ObjectParameter("PK_iPhanquyenID", pK_iPhanquyenID) :
                new ObjectParameter("PK_iPhanquyenID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PhanquyenModel>("spPhanquyen_GetByPK", mergeOption, pK_iPhanquyenIDParameter);
        }
    
        public virtual ObjectResult<Nullable<long>> spPhanquyen_Insert(Nullable<long> fK_iNguoidungID, Nullable<int> fK_iQuyenID, Nullable<System.DateTime> tNgaybatdau, Nullable<System.DateTime> tNgayketthuc)
        {
            var fK_iNguoidungIDParameter = fK_iNguoidungID.HasValue ?
                new ObjectParameter("FK_iNguoidungID", fK_iNguoidungID) :
                new ObjectParameter("FK_iNguoidungID", typeof(long));
    
            var fK_iQuyenIDParameter = fK_iQuyenID.HasValue ?
                new ObjectParameter("FK_iQuyenID", fK_iQuyenID) :
                new ObjectParameter("FK_iQuyenID", typeof(int));
    
            var tNgaybatdauParameter = tNgaybatdau.HasValue ?
                new ObjectParameter("tNgaybatdau", tNgaybatdau) :
                new ObjectParameter("tNgaybatdau", typeof(System.DateTime));
    
            var tNgayketthucParameter = tNgayketthuc.HasValue ?
                new ObjectParameter("tNgayketthuc", tNgayketthuc) :
                new ObjectParameter("tNgayketthuc", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("spPhanquyen_Insert", fK_iNguoidungIDParameter, fK_iQuyenIDParameter, tNgaybatdauParameter, tNgayketthucParameter);
        }
    
        public virtual int spPhanquyen_UpdateByPK(Nullable<long> pK_iPhanquyenID, Nullable<long> fK_iNguoidungID, Nullable<int> fK_iQuyenID, Nullable<System.DateTime> tNgaybatdau, Nullable<System.DateTime> tNgayketthuc)
        {
            var pK_iPhanquyenIDParameter = pK_iPhanquyenID.HasValue ?
                new ObjectParameter("PK_iPhanquyenID", pK_iPhanquyenID) :
                new ObjectParameter("PK_iPhanquyenID", typeof(long));
    
            var fK_iNguoidungIDParameter = fK_iNguoidungID.HasValue ?
                new ObjectParameter("FK_iNguoidungID", fK_iNguoidungID) :
                new ObjectParameter("FK_iNguoidungID", typeof(long));
    
            var fK_iQuyenIDParameter = fK_iQuyenID.HasValue ?
                new ObjectParameter("FK_iQuyenID", fK_iQuyenID) :
                new ObjectParameter("FK_iQuyenID", typeof(int));
    
            var tNgaybatdauParameter = tNgaybatdau.HasValue ?
                new ObjectParameter("tNgaybatdau", tNgaybatdau) :
                new ObjectParameter("tNgaybatdau", typeof(System.DateTime));
    
            var tNgayketthucParameter = tNgayketthuc.HasValue ?
                new ObjectParameter("tNgayketthuc", tNgayketthuc) :
                new ObjectParameter("tNgayketthuc", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spPhanquyen_UpdateByPK", pK_iPhanquyenIDParameter, fK_iNguoidungIDParameter, fK_iQuyenIDParameter, tNgaybatdauParameter, tNgayketthucParameter);
        }
    
        public virtual int spQuyen_DeleteByPK(Nullable<int> pK_iQuyenID)
        {
            var pK_iQuyenIDParameter = pK_iQuyenID.HasValue ?
                new ObjectParameter("PK_iQuyenID", pK_iQuyenID) :
                new ObjectParameter("PK_iQuyenID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spQuyen_DeleteByPK", pK_iQuyenIDParameter);
        }
    
        public virtual ObjectResult<QuyenModel> spQuyen_GetByPK(Nullable<int> pK_iQuyenID)
        {
            var pK_iQuyenIDParameter = pK_iQuyenID.HasValue ?
                new ObjectParameter("PK_iQuyenID", pK_iQuyenID) :
                new ObjectParameter("PK_iQuyenID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<QuyenModel>("spQuyen_GetByPK", pK_iQuyenIDParameter);
        }
    
        public virtual ObjectResult<QuyenModel> spQuyen_GetByPK(Nullable<int> pK_iQuyenID, MergeOption mergeOption)
        {
            var pK_iQuyenIDParameter = pK_iQuyenID.HasValue ?
                new ObjectParameter("PK_iQuyenID", pK_iQuyenID) :
                new ObjectParameter("PK_iQuyenID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<QuyenModel>("spQuyen_GetByPK", mergeOption, pK_iQuyenIDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> spQuyen_Insert(string sTenQuyen, string sYnghia)
        {
            var sTenQuyenParameter = sTenQuyen != null ?
                new ObjectParameter("sTenQuyen", sTenQuyen) :
                new ObjectParameter("sTenQuyen", typeof(string));
    
            var sYnghiaParameter = sYnghia != null ?
                new ObjectParameter("sYnghia", sYnghia) :
                new ObjectParameter("sYnghia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("spQuyen_Insert", sTenQuyenParameter, sYnghiaParameter);
        }
    
        public virtual int spQuyen_UpdateByPK(Nullable<int> pK_iQuyenID, string sTenQuyen, string sYnghia)
        {
            var pK_iQuyenIDParameter = pK_iQuyenID.HasValue ?
                new ObjectParameter("PK_iQuyenID", pK_iQuyenID) :
                new ObjectParameter("PK_iQuyenID", typeof(int));
    
            var sTenQuyenParameter = sTenQuyen != null ?
                new ObjectParameter("sTenQuyen", sTenQuyen) :
                new ObjectParameter("sTenQuyen", typeof(string));
    
            var sYnghiaParameter = sYnghia != null ?
                new ObjectParameter("sYnghia", sYnghia) :
                new ObjectParameter("sYnghia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spQuyen_UpdateByPK", pK_iQuyenIDParameter, sTenQuyenParameter, sYnghiaParameter);
        }
    
        public virtual int spSanpham_DeleteByPK(Nullable<long> pK_iSanphamID)
        {
            var pK_iSanphamIDParameter = pK_iSanphamID.HasValue ?
                new ObjectParameter("PK_iSanphamID", pK_iSanphamID) :
                new ObjectParameter("PK_iSanphamID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spSanpham_DeleteByPK", pK_iSanphamIDParameter);
        }
    
        public virtual ObjectResult<SanphamModel> spSanpham_GetByFK_iLoaiSanphamID(Nullable<int> fK_iLoaiSanphamID)
        {
            var fK_iLoaiSanphamIDParameter = fK_iLoaiSanphamID.HasValue ?
                new ObjectParameter("FK_iLoaiSanphamID", fK_iLoaiSanphamID) :
                new ObjectParameter("FK_iLoaiSanphamID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SanphamModel>("spSanpham_GetByFK_iLoaiSanphamID", fK_iLoaiSanphamIDParameter);
        }
    
        public virtual ObjectResult<SanphamModel> spSanpham_GetByFK_iLoaiSanphamID(Nullable<int> fK_iLoaiSanphamID, MergeOption mergeOption)
        {
            var fK_iLoaiSanphamIDParameter = fK_iLoaiSanphamID.HasValue ?
                new ObjectParameter("FK_iLoaiSanphamID", fK_iLoaiSanphamID) :
                new ObjectParameter("FK_iLoaiSanphamID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SanphamModel>("spSanpham_GetByFK_iLoaiSanphamID", mergeOption, fK_iLoaiSanphamIDParameter);
        }
    
        public virtual ObjectResult<SanphamModel> spSanpham_GetByPK(Nullable<long> pK_iSanphamID)
        {
            var pK_iSanphamIDParameter = pK_iSanphamID.HasValue ?
                new ObjectParameter("PK_iSanphamID", pK_iSanphamID) :
                new ObjectParameter("PK_iSanphamID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SanphamModel>("spSanpham_GetByPK", pK_iSanphamIDParameter);
        }
    
        public virtual ObjectResult<SanphamModel> spSanpham_GetByPK(Nullable<long> pK_iSanphamID, MergeOption mergeOption)
        {
            var pK_iSanphamIDParameter = pK_iSanphamID.HasValue ?
                new ObjectParameter("PK_iSanphamID", pK_iSanphamID) :
                new ObjectParameter("PK_iSanphamID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SanphamModel>("spSanpham_GetByPK", mergeOption, pK_iSanphamIDParameter);
        }
    
        public virtual ObjectResult<Nullable<long>> spSanpham_Insert(string sTenSanpham, string sMota, Nullable<int> iSoluongg, string sXuatxu, string sHinhanh, Nullable<int> fK_iLoaiSanphamID, Nullable<bool> isNgungcungcap, Nullable<System.DateTime> tNgaysanxuat, Nullable<System.DateTime> tHansudung)
        {
            var sTenSanphamParameter = sTenSanpham != null ?
                new ObjectParameter("sTenSanpham", sTenSanpham) :
                new ObjectParameter("sTenSanpham", typeof(string));
    
            var sMotaParameter = sMota != null ?
                new ObjectParameter("sMota", sMota) :
                new ObjectParameter("sMota", typeof(string));
    
            var iSoluonggParameter = iSoluongg.HasValue ?
                new ObjectParameter("iSoluongg", iSoluongg) :
                new ObjectParameter("iSoluongg", typeof(int));
    
            var sXuatxuParameter = sXuatxu != null ?
                new ObjectParameter("sXuatxu", sXuatxu) :
                new ObjectParameter("sXuatxu", typeof(string));
    
            var sHinhanhParameter = sHinhanh != null ?
                new ObjectParameter("sHinhanh", sHinhanh) :
                new ObjectParameter("sHinhanh", typeof(string));
    
            var fK_iLoaiSanphamIDParameter = fK_iLoaiSanphamID.HasValue ?
                new ObjectParameter("FK_iLoaiSanphamID", fK_iLoaiSanphamID) :
                new ObjectParameter("FK_iLoaiSanphamID", typeof(int));
    
            var isNgungcungcapParameter = isNgungcungcap.HasValue ?
                new ObjectParameter("isNgungcungcap", isNgungcungcap) :
                new ObjectParameter("isNgungcungcap", typeof(bool));
    
            var tNgaysanxuatParameter = tNgaysanxuat.HasValue ?
                new ObjectParameter("tNgaysanxuat", tNgaysanxuat) :
                new ObjectParameter("tNgaysanxuat", typeof(System.DateTime));
    
            var tHansudungParameter = tHansudung.HasValue ?
                new ObjectParameter("tHansudung", tHansudung) :
                new ObjectParameter("tHansudung", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("spSanpham_Insert", sTenSanphamParameter, sMotaParameter, iSoluonggParameter, sXuatxuParameter, sHinhanhParameter, fK_iLoaiSanphamIDParameter, isNgungcungcapParameter, tNgaysanxuatParameter, tHansudungParameter);
        }
    
        public virtual int spSanpham_UpdateByPK(Nullable<long> pK_iSanphamID, string sTenSanpham, string sMota, Nullable<int> iSoluongg, string sXuatxu, string sHinhanh, Nullable<int> fK_iLoaiSanphamID, Nullable<bool> isNgungcungcap)
        {
            var pK_iSanphamIDParameter = pK_iSanphamID.HasValue ?
                new ObjectParameter("PK_iSanphamID", pK_iSanphamID) :
                new ObjectParameter("PK_iSanphamID", typeof(long));
    
            var sTenSanphamParameter = sTenSanpham != null ?
                new ObjectParameter("sTenSanpham", sTenSanpham) :
                new ObjectParameter("sTenSanpham", typeof(string));
    
            var sMotaParameter = sMota != null ?
                new ObjectParameter("sMota", sMota) :
                new ObjectParameter("sMota", typeof(string));
    
            var iSoluonggParameter = iSoluongg.HasValue ?
                new ObjectParameter("iSoluongg", iSoluongg) :
                new ObjectParameter("iSoluongg", typeof(int));
    
            var sXuatxuParameter = sXuatxu != null ?
                new ObjectParameter("sXuatxu", sXuatxu) :
                new ObjectParameter("sXuatxu", typeof(string));
    
            var sHinhanhParameter = sHinhanh != null ?
                new ObjectParameter("sHinhanh", sHinhanh) :
                new ObjectParameter("sHinhanh", typeof(string));
    
            var fK_iLoaiSanphamIDParameter = fK_iLoaiSanphamID.HasValue ?
                new ObjectParameter("FK_iLoaiSanphamID", fK_iLoaiSanphamID) :
                new ObjectParameter("FK_iLoaiSanphamID", typeof(int));
    
            var isNgungcungcapParameter = isNgungcungcap.HasValue ?
                new ObjectParameter("isNgungcungcap", isNgungcungcap) :
                new ObjectParameter("isNgungcungcap", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spSanpham_UpdateByPK", pK_iSanphamIDParameter, sTenSanphamParameter, sMotaParameter, iSoluonggParameter, sXuatxuParameter, sHinhanhParameter, fK_iLoaiSanphamIDParameter, isNgungcungcapParameter);
        }
    }
}
