//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanSinhTo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanphamModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanphamModel()
        {
            this.tblBanggias = new HashSet<BanggiaModel>();
            this.tblChitietHoadonxuats = new HashSet<ChitietHoadonxuatModel>();
            this.tblChitietSanphams = new HashSet<ChitietSanphamModel>();
            this.tblKhuyenmais = new HashSet<KhuyenmaiModel>();
        }
    
        public long PK_iSanphamID { get; set; }
        public string sTenSanpham { get; set; }
        public string sMota { get; set; }
        public int iSoluong { get; set; }
        public string sXuatxu { get; set; }
        public string sHinhanh { get; set; }
        public int FK_iLoaiSanphamID { get; set; }
        public bool isNgungcungcap { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BanggiaModel> tblBanggias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChitietHoadonxuatModel> tblChitietHoadonxuats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChitietSanphamModel> tblChitietSanphams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhuyenmaiModel> tblKhuyenmais { get; set; }
        public virtual LoaiSanphamModel tblLoaiSanpham { get; set; }
    }
}
